=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/main/xsd/RDFSchema/RDFSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- XML Schema representing the Schema of an RDF Source in ER-->
<!-- Author: Klitos Christodoulou -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<!-- Complex Element: RDFEntityTypes -->	
	<xs:element name="RDFEntityTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="1" ref="RDFSchemaMetadata"/>
				<xs:element maxOccurs="unbounded" minOccurs="1"	ref="RDFEntityType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<!-- Store Information about NameSpaces -->
	<xs:element name="RDFSchemaMetadata">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="unbounded" minOccurs="0" name="NameSpace" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element: RDFEntityType -->
	<xs:element name="RDFEntityType">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="1" minOccurs="1" name="RDFEntityTypeName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFEntityType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="MultiAttrOfRDFEntityType" />	          
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="CompositeAttrOfRDFEntityType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFBinaryRelationshipType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFWeakEntityType" />
			</xs:sequence>
			<xs:attribute name="rdftype" type="xs:anyURI"/>
		</xs:complexType>
	</xs:element>

	<!-- Complex Element (Attribute) : SimpleAttrOfRDFEntityType -->
	<xs:element name="SimpleAttrOfRDFEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element (Attribute) : MultiAttrOfRDFEntityType -->
	<xs:element name="MultiAttrOfRDFEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>

	<!-- Complex Element: CompositeAttrOfRDFEntityType -->
	<xs:element name="CompositeAttrOfRDFEntityType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="CompositeAttrName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFEntityType" />
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
    <!-- Complex Element: RDFBinaryRelationshipType -->
	<xs:element name="RDFBinaryRelationshipType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="RDFRelationshipName" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="FromRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="ToRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="CardinalityRatio" type="xs:string" />	          
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element: RDFWeakEntityType -->
	<xs:element name="RDFWeakEntityType">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="1" minOccurs="1" name="RDFWeakEntityTypeName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFWeakEntityType" />
              <xs:element maxOccurs="unbounded" minOccurs="0" name="MultiAttrOfRDFWeakEntityType" type="xs:string" />
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFIdentifiedRelationshipType" />	   
			</xs:sequence>
			<xs:attribute name="rdftype" type="xs:anyURI" use="optional"/>
		</xs:complexType>
	</xs:element>	
	
	<!-- Complex Element (Attribute) : SimpleAttrOfRDFWeakEntityType -->
	<xs:element name="SimpleAttrOfRDFWeakEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>
	
    <!-- Complex Element: RDFIdentifiedRelationshipType for WeakEntities -->
	<xs:element name="RDFIdentifiedRelationshipType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="RDFRelationshipName" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="FromRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="ToRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="CardinalityRatio" type="xs:string" />	          
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>	
	
</xs:schema>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/target/test-classes/schemas/jamendoRDFSchema.xml
<?xml version="1.0"?>
<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">
  <!-- This is the inferred Schema of Jamendo -->
  
  <RDFSchemaMetadata>
    <NameSpace>tags=http://www.holygoat.co.uk/owl/redwood/0.1/tags/</NameSpace>
    <NameSpace>dc=http://purl.org/dc/elements/1.1/</NameSpace>
    <NameSpace>time=http://www.w3.org/2006/time#</NameSpace>
    <NameSpace>tl=http://purl.org/NET/c4dm/timeline.owl#</NameSpace>
    <NameSpace>mo=http://purl.org/ontology/mo/</NameSpace>
    <NameSpace>foaf=http://xmlns.com/foaf/0.1/</NameSpace>
    <NameSpace>event=http://purl.org/NET/c4dm/event.owl#</NameSpace>
    <NameSpace>xsd=http://www.w3.org/2001/XMLSchema#</NameSpace>
    <NameSpace>rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#</NameSpace>
  </RDFSchemaMetadata>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Record">
    <RDFEntityTypeName>Record</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">description</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">image</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">date</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">maker</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">track</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">taggedWithTag</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">available_as</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>maker</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>MusicArtist</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>track</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">
      <RDFRelationshipName>taggedWithTag</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>Tag</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>available_as</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>ED2K</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Lyrics">
    <RDFEntityTypeName>Lyrics</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">text</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/MusicArtist">
    <RDFEntityTypeName>MusicArtist</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">img</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">biography</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">homepage</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">based_near</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">made</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>made</RDFRelationshipName>
      <FromRDFEntityType>MusicArtist</FromRDFEntityType>
      <ToRDFEntityType>Record</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Signal">
    <RDFEntityTypeName>Signal</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">time</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">published_as</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>time</RDFRelationshipName>
      <FromRDFEntityType>Signal</FromRDFEntityType>
      <ToRDFEntityType>Interval</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>published_as</RDFRelationshipName>
      <FromRDFEntityType>Signal</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.w3.org/2006/time#Interval">
    <RDFEntityTypeName>Interval</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/NET/c4dm/timeline.owl#">onTimeLine</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Torrent">
    <RDFEntityTypeName>Torrent</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Track">
    <RDFEntityTypeName>Track</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">track_number</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">license</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">available_as</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>license</RDFRelationshipName>
      <FromRDFEntityType>Track</FromRDFEntityType>
      <ToRDFEntityType>Document</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>available_as</RDFRelationshipName>
      <FromRDFEntityType>Track</FromRDFEntityType>
      <ToRDFEntityType>Playlist</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/ED2K">
    <RDFEntityTypeName>ED2K</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.holygoat.co.uk/owl/redwood/0.1/tags/Tag">
    <RDFEntityTypeName>Tag</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">tagName</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Playlist">
    <RDFEntityTypeName>Playlist</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://xmlns.com/foaf/0.1/Document">
    <RDFEntityTypeName>Document</RDFEntityTypeName>
  </RDFEntityType>
</RDFEntityTypes>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/main/xml/RDFSchema/RDFSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">

<!-- I need to store each of the vocabularies URIs as metadata  -->
<!-- I need to store each of the URIs of the   -->
     <RDFSchemaMetadata>
     	<NameSpace>xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"</NameSpace>   
     	<NameSpace>xmlns:vocab="http://localhost:2020/vocab/resource/</NameSpace>
     </RDFSchemaMetadata>

	<RDFEntityType uri="example.com">
    	<RDFEntityTypeName>Student</RDFEntityTypeName>
    	<SimpleAttrOfRDFEntityType namespace="vocab">Name</SimpleAttrOfRDFEntityType>
    	<SimpleAttrOfRDFEntityType namespace="vocab">Lastname</SimpleAttrOfRDFEntityType>
    	<MultiAttrOfRDFEntityType namespace="vocab">PhoneNumber</MultiAttrOfRDFEntityType>
    	<CompositeAttrOfRDFEntityType namespace="vocab">
    		<!-- Address from BNode thus no URI -->
      		<CompositeAttrName>Address</CompositeAttrName>
      		<SimpleAttrOfRDFEntityType namespace="vocab">City</SimpleAttrOfRDFEntityType>
      		<SimpleAttrOfRDFEntityType namespace="vocab">Postcode</SimpleAttrOfRDFEntityType>
    	</CompositeAttrOfRDFEntityType>
   		<RDFBinaryRelationshipType namespace="vocab">
      		<RDFRelationshipName>Register_To</RDFRelationshipName>
      		<FromRDFEntityType>Students</FromRDFEntityType>
    		<ToRDFEntityType>Universities</ToRDFEntityType>
      		<CardinalityRatio>1:N</CardinalityRatio>
    	</RDFBinaryRelationshipType>
    	<RDFWeakEntityType>
      		<RDFWeakEntityTypeName>Category</RDFWeakEntityTypeName>
      		<SimpleAttrOfRDFWeakEntityType namespace="vocab">description</SimpleAttrOfRDFWeakEntityType>
      		<SimpleAttrOfRDFWeakEntityType namespace="vocab">name</SimpleAttrOfRDFWeakEntityType>
      		<MultiAttrOfRDFWeakEntityType>PhoneNumber</MultiAttrOfRDFWeakEntityType>
      		<RDFIdentifiedRelationshipType>
        		<RDFRelationshipName>Register_To</RDFRelationshipName>
        		<FromRDFEntityType>Universities</FromRDFEntityType>
        		<ToRDFEntityType>Universities</ToRDFEntityType>
        		<CardinalityRatio>1:N</CardinalityRatio>
      		</RDFIdentifiedRelationshipType>
    	</RDFWeakEntityType>    
  </RDFEntityType>

</RDFEntityTypes>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/test/resources/schemas/studentsRDFSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- RDF Schema: Students RDF -->

<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">

  <RDFSchemaMetadata>
    <NameSpace>db=http://localhost:2020/</NameSpace>
    <NameSpace>rdfs=http://www.w3.org/2000/01/rdf-schema#</NameSpace>
    <NameSpace>owl=http://www.w3.org/2002/07/owl#</NameSpace>
    <NameSpace>map=file:///stdout#</NameSpace>
    <NameSpace>xsd=http://www.w3.org/2001/XMLSchema#</NameSpace>
    <NameSpace>rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#</NameSpace>
    <NameSpace>vocab=http://localhost:2020/vocab/resource/</NameSpace>
  </RDFSchemaMetadata>
  <RDFEntityType rdftype="http://localhost:2020/vocab/resource/phonenumber">
    <RDFEntityTypeName>phonenumber</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">phonenumber_number</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">phonenumber_phonetype</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">phonenumber_StdnID</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://localhost:2020/vocab/resource/">
      <RDFRelationshipName>phonenumber_StdnID</RDFRelationshipName>
      <FromRDFEntityType>phonenumber</FromRDFEntityType>
      <ToRDFEntityType>students</ToRDFEntityType>
      <CardinalityRatio>1:N</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://localhost:2020/vocab/resource/students">
    <RDFEntityTypeName>students</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_Homepage</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_Type</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_LastName</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_StdnID</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_FirstName</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_Email</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">students_RegisterTo</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">enrol</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://localhost:2020/vocab/resource/">
      <RDFRelationshipName>students_RegisterTo</RDFRelationshipName>
      <FromRDFEntityType>students</FromRDFEntityType>
      <ToRDFEntityType>universities</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://localhost:2020/vocab/resource/">
      <RDFRelationshipName>enrol</RDFRelationshipName>
      <FromRDFEntityType>students</FromRDFEntityType>
      <ToRDFEntityType>modules</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://localhost:2020/vocab/resource/modules">
    <RDFEntityTypeName>modules</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">modules_Description</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">modules_ModuleID</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">modules_ModuleName</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">modules_Credits</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://localhost:2020/vocab/resource/universities">
    <RDFEntityTypeName>universities</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">universities_Name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">universities_Type</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">universities_UniID</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://localhost:2020/vocab/resource/">universities_URI</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
</RDFEntityTypes>
