=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/main/xsd/RDFSchema/RDFSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- XML Schema representing the Schema of an RDF Source in ER-->
<!-- Author: Klitos Christodoulou -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<!-- Complex Element: RDFEntityTypes -->	
	<xs:element name="RDFEntityTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="1" ref="RDFSchemaMetadata"/>
				<xs:element maxOccurs="unbounded" minOccurs="1"	ref="RDFEntityType" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<!-- Store Information about NameSpaces -->
	<xs:element name="RDFSchemaMetadata">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="unbounded" minOccurs="0" name="NameSpace" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element: RDFEntityType -->
	<xs:element name="RDFEntityType">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="1" minOccurs="1" name="RDFEntityTypeName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFEntityType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="MultiAttrOfRDFEntityType" />	          
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="CompositeAttrOfRDFEntityType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFBinaryRelationshipType" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFWeakEntityType" />
			</xs:sequence>
			<xs:attribute name="rdftype" type="xs:anyURI"/>
		</xs:complexType>
	</xs:element>

	<!-- Complex Element (Attribute) : SimpleAttrOfRDFEntityType -->
	<xs:element name="SimpleAttrOfRDFEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element (Attribute) : MultiAttrOfRDFEntityType -->
	<xs:element name="MultiAttrOfRDFEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>

	<!-- Complex Element: CompositeAttrOfRDFEntityType -->
	<xs:element name="CompositeAttrOfRDFEntityType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="CompositeAttrName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFEntityType" />
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
    <!-- Complex Element: RDFBinaryRelationshipType -->
	<xs:element name="RDFBinaryRelationshipType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="RDFRelationshipName" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="FromRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="ToRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="CardinalityRatio" type="xs:string" />	          
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	
	<!-- Complex Element: RDFWeakEntityType -->
	<xs:element name="RDFWeakEntityType">
		<xs:complexType>
			<xs:sequence>
	          <xs:element maxOccurs="1" minOccurs="1" name="RDFWeakEntityTypeName" type="xs:string" />
	          <xs:element maxOccurs="unbounded" minOccurs="0" ref="SimpleAttrOfRDFWeakEntityType" />
              <xs:element maxOccurs="unbounded" minOccurs="0" name="MultiAttrOfRDFWeakEntityType" type="xs:string" />
              <xs:element maxOccurs="unbounded" minOccurs="0" ref="RDFIdentifiedRelationshipType" />	   
			</xs:sequence>
			<xs:attribute name="rdftype" type="xs:anyURI" use="optional"/>
		</xs:complexType>
	</xs:element>	
	
	<!-- Complex Element (Attribute) : SimpleAttrOfRDFWeakEntityType -->
	<xs:element name="SimpleAttrOfRDFWeakEntityType">
 		<xs:complexType>
  			<xs:simpleContent>
   				<xs:extension base="xs:string">
    				<xs:attribute name="namespace" type="xs:string" use="optional"/>
   				</xs:extension>
 			 </xs:simpleContent>
 		</xs:complexType>
	</xs:element>
	
    <!-- Complex Element: RDFIdentifiedRelationshipType for WeakEntities -->
	<xs:element name="RDFIdentifiedRelationshipType">
		<xs:complexType>
			<xs:sequence>
		      <xs:element maxOccurs="1" minOccurs="1" name="RDFRelationshipName" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="FromRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="ToRDFEntityType" type="xs:string" />
	          <xs:element maxOccurs="1" minOccurs="0" name="CardinalityRatio" type="xs:string" />	          
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string"/>
		</xs:complexType>
	</xs:element>	
	
</xs:schema>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/target/test-classes/schemas/magnatuneRDFSchema.xml
<?xml version="1.0"?>
<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">

  <RDFSchemaMetadata>
    <NameSpace>dc=http://purl.org/dc/elements/1.1/</NameSpace>
    <NameSpace>db=http://dbtune.org/magnatune/</NameSpace>
    <NameSpace>tl=http://purl.org/NET/c4dm/timeline.owl#</NameSpace>
    <NameSpace>mo=http://purl.org/ontology/mo/</NameSpace>
    <NameSpace>foaf=http://xmlns.com/foaf/0.1/</NameSpace>
    <NameSpace>rdfs=http://www.w3.org/2000/01/rdf-schema#</NameSpace>
    <NameSpace>time=http://www.w3.org/TR/owl-time/</NameSpace>
    <NameSpace>bio=http://purl.org/vocab/bio/0.1/</NameSpace>
    <NameSpace>event=http://purl.org/NET/c4dm/event.owl#</NameSpace>
    <NameSpace>d2r=http://sites.wiwiss.fu-berlin.de/suhl/bizer/d2r-server/config.rdf#</NameSpace>
    <NameSpace>map=file:///home/moustaki/work/workspace/opendata/d2r-server-0.3.1/mapping.n3#</NameSpace>
    <NameSpace>xsd=http://www.w3.org/2001/XMLSchema#</NameSpace>
    <NameSpace>rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#</NameSpace>
    <NameSpace>vocab=http://dbtune.org/magnatune/vocab/</NameSpace>
  </RDFSchemaMetadata>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/MusicArtist">
    <RDFEntityTypeName>MusicArtist</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/vocab/bio/0.1/">olb</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">description</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">img</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">homepage</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">based_near</SimpleAttrOfRDFEntityType>
    <MultiAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">name</MultiAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.w3.org/TR/owl-time/Interval">
    <RDFEntityTypeName>Interval</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/NET/c4dm/timeline.owl#">duration</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/NET/c4dm/timeline.owl#">onTimeLine</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/NET/c4dm/timeline.owl#">
      <RDFRelationshipName>onTimeLine</RDFRelationshipName>
      <FromRDFEntityType>Interval</FromRDFEntityType>
      <ToRDFEntityType>RelativeTimeLine</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Signal">
    <RDFEntityTypeName>Signal</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">time</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">published_as</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>time</RDFRelationshipName>
      <FromRDFEntityType>Signal</FromRDFEntityType>
      <ToRDFEntityType>Interval</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>published_as</RDFRelationshipName>
      <FromRDFEntityType>Signal</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Record">
    <RDFEntityTypeName>Record</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">publishing_location</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">maker</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">track</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>maker</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>MusicArtist</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>track</RDFRelationshipName>
      <FromRDFEntityType>Record</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Track">
    <RDFEntityTypeName>Track</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">created</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">paid_download</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">track_number</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">available_as</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">maker</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>maker</RDFRelationshipName>
      <FromRDFEntityType>Track</FromRDFEntityType>
      <ToRDFEntityType>MusicArtist</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Performance">
    <RDFEntityTypeName>Performance</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/NET/c4dm/event.owl#">place</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">recorded_as</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">performer</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>recorded_as</RDFRelationshipName>
      <FromRDFEntityType>Performance</FromRDFEntityType>
      <ToRDFEntityType>Signal</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>performer</RDFRelationshipName>
      <FromRDFEntityType>Performance</FromRDFEntityType>
      <ToRDFEntityType>MusicArtist</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/NET/c4dm/timeline.owl#RelativeTimeLine">
    <RDFEntityTypeName>RelativeTimeLine</RDFEntityTypeName>
  </RDFEntityType>
</RDFEntityTypes>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/target/test-classes/schemas/jamento_001_mutation.xml
<?xml version="1.0"?>
<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">
  <!-- This is the variant Schema of Jamendo -->

  <RDFSchemaMetadata>
    <NameSpace>tags=http://www.holygoat.co.uk/owl/redwood/0.1/tags/</NameSpace>
    <NameSpace>dc=http://purl.org/dc/elements/1.1/</NameSpace>
    <NameSpace>time=http://www.w3.org/2006/time#</NameSpace>
    <NameSpace>tl=http://purl.org/NET/c4dm/timeline.owl#</NameSpace>
    <NameSpace>mo=http://purl.org/ontology/mo/</NameSpace>
    <NameSpace>foaf=http://xmlns.com/foaf/0.1/</NameSpace>
    <NameSpace>event=http://purl.org/NET/c4dm/event.owl#</NameSpace>
    <NameSpace>xsd=http://www.w3.org/2001/XMLSchema#</NameSpace>
    <NameSpace>rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#</NameSpace>
  </RDFSchemaMetadata>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/MusicalManifestation">
    <RDFEntityTypeName>MusicalManifestation</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">description</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">image</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">date</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">maker</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">has_track</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">taggedWithTag</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">availableAs</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>maker</RDFRelationshipName>
      <FromRDFEntityType>MusicalManifestation</FromRDFEntityType>
      <ToRDFEntityType>Agent</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>has_track</RDFRelationshipName>
      <FromRDFEntityType>MusicalManifestation</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">
      <RDFRelationshipName>taggedWithTag</RDFRelationshipName>
      <FromRDFEntityType>MusicalManifestation</FromRDFEntityType>
      <ToRDFEntityType>Tag</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>availableAs</RDFRelationshipName>
      <FromRDFEntityType>MusicalManifestation</FromRDFEntityType>
      <ToRDFEntityType>Medium</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Lyrics">
    <RDFEntityTypeName>Lyrics</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">text</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://xmlns.com/foaf/0.1/Agent">
    <RDFEntityTypeName>Agent</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">img</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">discography</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">weblog</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">based_near</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://xmlns.com/foaf/0.1/">made</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://xmlns.com/foaf/0.1/">
      <RDFRelationshipName>made</RDFRelationshipName>
      <FromRDFEntityType>Agent</FromRDFEntityType>
      <ToRDFEntityType>MusicalManifestation</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/AnalogSignal">
    <RDFEntityTypeName>AnalogSignal</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">signalTime</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">publishedAs</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>signalTime</RDFRelationshipName>
      <FromRDFEntityType>AnalogSignal</FromRDFEntityType>
      <ToRDFEntityType>TemporalEntity</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>publishedAs</RDFRelationshipName>
      <FromRDFEntityType>AnalogSignal</FromRDFEntityType>
      <ToRDFEntityType>Track</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.w3.org/2006/time#TemporalEntity">
    <RDFEntityTypeName>TemporalEntity</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/NET/c4dm/timeline.owl#">onTimeLine</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Torrent">
    <RDFEntityTypeName>Torrent</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Track">
    <RDFEntityTypeName>Track</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">title</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">trackNum</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">license</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/ontology/mo/">availableAs</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>license</RDFRelationshipName>
      <FromRDFEntityType>Track</FromRDFEntityType>
      <ToRDFEntityType>Document</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
    <RDFBinaryRelationshipType namespace="http://purl.org/ontology/mo/">
      <RDFRelationshipName>availableAs</RDFRelationshipName>
      <FromRDFEntityType>Track</FromRDFEntityType>
      <ToRDFEntityType>Playlist</ToRDFEntityType>
      <CardinalityRatio>N:M</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Medium">
    <RDFEntityTypeName>Medium</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.holygoat.co.uk/owl/redwood/0.1/tags/Tag">
    <RDFEntityTypeName>Tag</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://www.holygoat.co.uk/owl/redwood/0.1/tags/">tagName</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://purl.org/ontology/mo/Playlist">
    <RDFEntityTypeName>Playlist</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://purl.org/dc/elements/1.1/">format</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://xmlns.com/foaf/0.1/Document">
    <RDFEntityTypeName>Document</RDFEntityTypeName>
  </RDFEntityType>
</RDFEntityTypes>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/test/resources/schemas/telegraphisRDFSchema.xml
<?xml version="1.0"?>
<!-- RDF Schema: telegraphics RDF -->
<RDFEntityTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RDFSchema.xsd">

  <RDFSchemaMetadata>
    <NameSpace>gn=http://www.geonames.org/ontology#</NameSpace>
    <NameSpace>metric=http://www.telegraphis.net/ontology/measurement/metric#</NameSpace>
    <NameSpace>money=http://telegraphis.net/ontology/money/money#</NameSpace>
    <NameSpace>owl=http://www.w3.org/2002/07/owl#</NameSpace>
    <NameSpace>rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#</NameSpace>
    <NameSpace>quantity=http://www.telegraphis.net/ontology/measurement/quantity#</NameSpace>
    <NameSpace>code=http://telegraphis.net/ontology/measurement/code#</NameSpace>
    <NameSpace>geographis=http://telegraphis.net/ontology/geography/geography#</NameSpace>
    <NameSpace>measurement=http://www.telegraphis.net/ontology/measurement/measurement#</NameSpace>
  </RDFSchemaMetadata>
  <RDFEntityType rdftype="http://www.geonames.org/ontology#Country">
    <RDFEntityTypeName>Country</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">isoAlpha3</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">isoAlpha2</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureCode</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureClass</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">isoNumeric</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">onContinent</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">population</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">currency</SimpleAttrOfRDFEntityType>
    <MultiAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">isoShortName</MultiAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://telegraphis.net/ontology/geography/geography#">
      <RDFRelationshipName>currency</RDFRelationshipName>
      <FromRDFEntityType>Country</FromRDFEntityType>
      <ToRDFEntityType>Currency</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://telegraphis.net/ontology/money/money#Currency">
    <RDFEntityTypeName>Currency</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">isoNumeric</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">minorExponent</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">isoAlpha</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">shortName</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">minorName</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">currencyOf</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://telegraphis.net/ontology/money/money#">
      <RDFRelationshipName>currencyOf</RDFRelationshipName>
      <FromRDFEntityType>Currency</FromRDFEntityType>
      <ToRDFEntityType>Country</ToRDFEntityType>
      <CardinalityRatio>1:N</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.telegraphis.net/ontology/geography/geography#Continent">
    <RDFEntityTypeName>Continent</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureClass</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureCode</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">population</SimpleAttrOfRDFEntityType>
  </RDFEntityType>
  <RDFEntityType rdftype="http://www.geonames.org/ontology#Capital">
    <RDFEntityTypeName>Capital</RDFEntityTypeName>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/money/money#">name</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureClass</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://www.geonames.org/ontology#">featureCode</SimpleAttrOfRDFEntityType>
    <SimpleAttrOfRDFEntityType namespace="http://telegraphis.net/ontology/geography/geography#">capitalOf</SimpleAttrOfRDFEntityType>
    <RDFBinaryRelationshipType namespace="http://telegraphis.net/ontology/geography/geography#">
      <RDFRelationshipName>capitalOf</RDFRelationshipName>
      <FromRDFEntityType>Capital</FromRDFEntityType>
      <ToRDFEntityType>Country</ToRDFEntityType>
      <CardinalityRatio>1:1</CardinalityRatio>
    </RDFBinaryRelationshipType>
  </RDFEntityType>
</RDFEntityTypes>
