=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/src/test/resources/schemas/arrayexschema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
  <xs:element name="accession" type="xs:string"/>
  <xs:element name="ef" type="xs:string"/>
  <xs:element name="efv" type="xs:string"/>
  <xs:element name="ensemblGeneId" type="xs:string"/>
  <xs:element name="ensemblProteinId" type="xs:string"/>
  <xs:element name="id" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="organism" type="xs:string"/>
  <xs:element name="pvalue" type="xs:decimal"/>
  <xs:element name="upExperiments" type="xs:integer" />
  <xs:element name="downExperiments" type="xs:integer"/>
  <xs:element name="nonDEExperiments" type="xs:integer" />
  <xs:element name="upPvalue" type="xs:decimal" />
  <xs:element name="downPvalue" type="xs:decimal" />


<!-- definition of complex elements -->
  <xs:element name="arrayexpress">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="results"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="ensemblProteinIds">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ensemblProteinId" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="accession" />
        <xs:element ref="pvalue" />
        <xs:element name="expression" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="experiments">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="experiment" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="expression">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="ef" />
        <xs:element ref="efv" />
        <xs:element ref="experiments" />
        <xs:element ref="upExperiments" />
        <xs:element ref="downExperiments" />
        <xs:element ref="nonDEExperiments" />
        <xs:element ref="upPvalue" />
        <xs:element ref="downPvalue" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="expressions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="expression" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="gene">
    <xs:complexType mixed="true">
      <xs:all>
        <xs:element ref="id" />
        <xs:element ref="name" />
        <xs:element ref="ensemblProteinIds" minOccurs="0"/>
        <xs:element ref="ensemblGeneId" />
        <xs:element ref="organism" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="result">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gene" />
        <xs:element ref="expressions" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="results">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="result" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Ivelize/Spreadsheet-Data-Integration-Framework/DSToolkit/iveBranch/target/test-classes/datasets/ArrayExpress.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- This document was created with Syntext Serna Free. -->
<arrayexpress xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="arrayexschema.xsd">
  <results>
    <result>
      <gene>
        <id>YFL032W</id>
        <name>YFL032W</name>
        <ensemblProteinIds>
          <ensemblProteinId>YFL032W</ensemblProteinId>
        </ensemblProteinIds>
        <ensemblGeneId>YFL032W</ensemblGeneId>
        <organism>Saccharomyces cerevisiae</organism>
      </gene>
      <expressions>
        <expression>
          <ef>growth_condition</ef>
          <efv>control</efv>
          <experiments>
            <experiment>
              <accession>E-GEOD-1311</accession>
              <pvalue>0.047000002</pvalue>
              <expression>DOWN</expression>
            </experiment>
          </experiments>
          <upExperiments>0</upExperiments>
          <downExperiments>1</downExperiments>
          <nonDEExperiments>0</nonDEExperiments>
          <upPvalue>1.0</upPvalue>
          <downPvalue>0.04700000211596489</downPvalue>
        </expression>
      </expressions>
    </result>
    <result>
      <gene>
        <ensemblProteinIds>
          <ensemblProteinId>YCR057C</ensemblProteinId>
        </ensemblProteinIds>
        <ensemblGeneId>YCR057C</ensemblGeneId>
        <organism>Saccharomyces cerevisiae</organism>
        <id>YCR057C</id>
        <name>PWP2</name>
      </gene>
      <expressions>
        <expression>
          <ef>growth_condition</ef>
          <efv>3 days in YPD (control)</efv>
          <experiments>
            <experiment>
              <accession>E-GEOD-8379</accession>
              <pvalue>0.0</pvalue>
              <expression>DOWN</expression>
            </experiment>
          </experiments>
          <upExperiments>0</upExperiments>
          <downExperiments>1</downExperiments>
          <nonDEExperiments>0</nonDEExperiments>
          <upPvalue>1.0</upPvalue>
          <downPvalue>0.0</downPvalue>
        </expression>
      </expressions>
    </result>
    <result>
      <gene>
        <ensemblProteinIds>
          <ensemblProteinId>YMR312W</ensemblProteinId>
        </ensemblProteinIds>
        <ensemblGeneId>YMR312W</ensemblGeneId>
        <organism>Saccharomyces cerevisiae</organism>
        <id>YMR312W</id>
        <name>ELP6</name>
      </gene>
      <expressions>
        <expression>
          <ef>growth_condition</ef>
          <efv>3 days in YPD (control)</efv>
          <experiments>
            <experiment>
              <accession>E-GEOD-8379</accession>
              <pvalue>0.0010</pvalue>
              <expression>DOWN</expression>
            </experiment>
          </experiments>
          <upExperiments>0</upExperiments>
          <downExperiments>1</downExperiments>
          <nonDEExperiments>0</nonDEExperiments>
          <upPvalue>1.0</upPvalue>
          <downPvalue>0.0010000000474974513</downPvalue>
        </expression>
      </expressions>
    </result>
    <result>
      <gene>
        <ensemblGeneId>YER086W</ensemblGeneId>
        <organism>Saccharomyces cerevisiae</organism>
        <id>YER086W</id>
        <name>ILV1</name>
      </gene>
      <expressions>
        <expression>
          <ef>growth_condition</ef>
          <efv>control</efv>
          <experiments>
            <experiment>
              <accession>E-GEOD-1312</accession>
              <pvalue>0.0</pvalue>
              <expression>UP</expression>
            </experiment>
            <experiment>
              <accession>E-GEOD-1313</accession>
              <pvalue>0.0</pvalue>
              <expression>UP</expression>
            </experiment>
          </experiments>
          <upExperiments>5</upExperiments>
          <downExperiments>0</downExperiments>
          <nonDEExperiments>0</nonDEExperiments>
          <upPvalue>0.0</upPvalue>
          <downPvalue>1.0</downPvalue>
        </expression>
      </expressions>
    </result>
  </results>
</arrayexpress>
